[build]
  base = "client" # Ruta de la carpeta del cliente
  command = "npm run build" # El comando que Netlify debe usar para construir el proyecto
  publish = "client/build" # La carpeta donde se encuentra el proyecto construido
